project_id = "anjfgswaktmemysfmyff"

[functions.omie-projetos]
verify_jwt = false

[functions.omie-financeiro]
verify_jwt = false

[functions.generate-budget-pdf]
verify_jwt = false

[functions.create-user]
verify_jwt = false
